version: "3"

services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/Caddyfile
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ACME_AGREE=true
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_KEY=${CF_APIKEY}
    entrypoint: "caddy --conf /etc/Caddyfile"
    networks:
      - web
    restart: always

  v2ray:
    image: v2fly/v2fly-core:latest
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    restart: always

networks:
  web:
