version: "3"

services:
  caddy:
    build:
      context: ./src/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/caddy/.caddy:/root/.caddy
      - ./src/caddy/Caddyfile:/etc/Caddyfile
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ACME_AGREE=true
      - CLOUDFLARE_EMAIL=xxx@yourmail.com
      - CLOUDFLARE_API_KEY=yourkey
    entrypoint: "caddy --conf /etc/Caddyfile"
    networks:
      - web
    restart: always

  v2ray:
    image: v2fly/v2fly-core:latest
    volumes:
      - ./src/v2ray/config.json:/etc/v2ray/config.json
      - /etc/localtime:/etc/localtime:ro
    networks:
      - web
    restart: always

networks:
  web: